name: spring app

on:
    push:
        branches:
            - main

jobs:

    build_app:

        name: build the spring app
        runs-on: ubuntu-latest

        steps:
            - name: checkout dir
              uses: actions/checkout@v3

            - name: setup java
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                cache: maven

            - name: build app
              run: mvn clean install
    
    image:

        name: docker image
        runs-on: ubuntu-latest
        needs: build_app

        steps:

            - name: checkout dir
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASS }}

            - name: build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/springapp:v${{github.run_number}}


            # - shell: bash
            #   run: ls -l

            # - name: cache for docker
            #   uses: actions/cache@v3
            #   with:
            #     path: var/lib/docker
            #     key: ${{runner.os}}-docker-${{hashFiles('**/Dockerfile')}}
            #     restore-keys: ${{runner.os}}-docker-

            # - name: docker login
            #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}

            # - name: docker build
            #   run: docker build -t ssrinivaspadala/spring_app .

            # - name: docker push
            #   run: docker push ssrinivaspadala/spring_app

            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v2

            # - name: Set up QEMU
            #   uses: docker/setup-qemu-action@v2
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v2
    

            # - name: Login to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_PASS }}

            # - name: build and push
            #   uses: docker/build-push-action@v4
            #   with:

            #     context: .
            #     push: true
            #     tags: ${{ secrets.DOCKER_USERNAME }}/springapp:v${{github.run_number}}